# Generated by Django 5.0.6 on 2024-05-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LeBrons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lebron', models.TextField(max_length=400)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('time_lebroned', models.DateField()),
                ('comments', models.TextField(max_length=200)),
                ('passes', models.PositiveIntegerField(default=0)),
                ('dunks', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
